dunovank/jupyter-themes

setup.py

shutil - part of the standard library - is used instead. Appears to install fine on Windows.

Removed dependency on library sh. 

---

jupyterthemes/__init__.py

This makes it so that the jupyter theme install runs without errors on python 3 as per described on issue #5.
I did some light testing, but @dunovank should make sure I didn't inadvertently break something that was working (namely cleaning up the file open mode flags). I did try installing the tool bar and that still doesn't work, but the script finishes executing.

Fix python print statements and write modes

---

jupyterthemes/__init__.py

When toolbar is enabled (-T), write() method was called twice (once after DEFAULT_TOOLBAR_STRING replacement, and once after DEFAULT_FONTSIZE_STRING replacement), creating duplicate lines in the css file. Now, replace() is called twice, but write() is called only once.

fixed duplicate lines in custom.css when toolbar is enabled

---

jupyterthemes/__init__.py

If I run `jt --help`, I get the following error because of an unescaped `%` in a help message: `ValueError: unsupported format character ')' (0x29) at index 24`.
I believe this is an argparse gotcha and the fix is to just to replace `%` with `%%`.
related [stackoverflow question](http://stackoverflow.com/questions/21168120/python-argparse-errors-with-in-help-string).
note: i'm using python 3.5.  I'm not sure that matters

fixed --help functionality

---

jupyterthemes/layout/cells.less

Currently, HTML output from `IPython.display.HTML` is displayed using the monospaced font rather than the text cell font.
master (grade3 theme):
this PR (grade3 theme):

switched html output from being monospace

---

README.md
jupyterthemes/__init__.py
jupyterthemes/stylefx.py

Hey!
These changes add the ability to use local themes from user's home directory the same way packaged themes are used. The directory structure of `site-packages/jupyterthemes` can be reflected in `~/.jupyter-themes` and extra/modified styles can be dropped there.
I also added the functionality of installing themes available in compatible `css` from either user (if user config dir exists) or packaged themes directory.
If both `.less` and `.css` versions of a certain theme exist, the `.less` version is used. If a theme exists as both a user theme and a global theme, the user theme is used. This came in handy when I wanted to slightly modify one of the packaged thems, I copied the `.less` file with the same file name to my own user themes directory and modified it without touching the one …

Add support to user less/precompiled themes

---

jupyterthemes/layout/completer.less
jupyterthemes/stylefx.py

Hi, 
While working on the [solarized theme as discussed](https://github.com/dunovank/jupyter-themes/issues/65)  (thanks for the encouragements btw way :) ) , I noticed the theme is currently not applied to the auto-complete menu. Namely, the font-size and background appear as default (see pictures below). 
I think we can fix that simply by applying the code style to the popup, with the `less` file attached. 
What do you think ? 
Also, good luck for your dissertation :) 
- chesterish
- grade3
- oceans16
- onedork 
- chesterish
- grade3
- oceans16
- onedork

applying theme to auto-complete menu

---

jupyterthemes/stylefx.py
requirements.txt
setup.py
tests/test_themes.py

Remove numpy dependency

---

jupyterthemes/stylefx.py

this fixes #71 
os.sep returns '/' for mac/linux but '\\' on windows, which breaks things when it is in the css

fix font 404 errors

---

jupyterthemes/styles/solarized-dark.less

fix for error from PR #103 
used colors from onedork theme, which although not same at all as solarized-dark, actually work well considering the warning/error/danger should be high contrast

added @item-### colors

---

jupyterthemes/stylefx.py

Use tempfile.mkstemp to create tempfiles

---

jupyterthemes/__init__.py

it cause `ValueError: unsupported format character ')'` when i execute `jt -h`,
is here should be written like this?

fix the invalid string format

---

jupyterthemes/layout/cells.less

This is my first PR to something. I've modified these cells in my own `custom.css` and it has the desired effect on my rendered markdown headings.

match rendered subheading styles for markdown

---

jupyterthemes/layout/notebook.less

Problem
- File encoding of notebook.less is UTF-8 and contains U+200B (ZERO
WIDTH_SPACE) which is not compatible with ASCII
- If system default encoding is not UTF-8, file read fails on
stylefx.py line 290
Applied solution
- used 'iconv -f UTF-8 -t ASCII' command to change file encoding
- U+200B character removed during conversion
Environment
- OS: run centos:7.3.1611 official docker image with a centos 7.3.1611 host
- Install python3 & jupyterthemes
- jt command fails
```
Traceback (most recent call last):
File "/root/.local/bin/jt", line 11, in <module>
sys.exit(main())
File "/root/.local/lib/python3.6/site-packages/jupyterthemes/__init__.py", line 305, in main
dfonts=args.defaultfonts)
File "/root/.local/lib/python3.6/site-packages/jupyterthemes/__init__.py", line 98, in install_theme …
```

Change layout/notebook.less file format from UTF-8 to ASCII

---

jupyterthemes/styles/chesterish.less
jupyterthemes/styles/grade3.less
jupyterthemes/styles/gruvboxd.less
jupyterthemes/styles/gruvboxl.less
jupyterthemes/styles/monokai.less
jupyterthemes/styles/oceans16.less
jupyterthemes/styles/onedork.less
jupyterthemes/styles/solarizedd.less
jupyterthemes/styles/solarizedl.less

Fix bug introduced in 9ba2240d.
Specifically, remove these two lines:
@nb-name-fg:            @button-bg;
@nb-name-hover:         @divider;
as they override the correct values by setting foreground color to background color

Fix bug introduced in 9ba2240d

---

jupyterthemes/styles/compiled/chesterish.css
jupyterthemes/styles/compiled/grade3.css
jupyterthemes/styles/compiled/gruvboxd.css
jupyterthemes/styles/compiled/gruvboxl.css
jupyterthemes/styles/compiled/monokai.css
jupyterthemes/styles/compiled/oceans16.css
jupyterthemes/styles/compiled/onedork.css
jupyterthemes/styles/compiled/solarizedd.css
jupyterthemes/styles/compiled/solarizedl.css

This resizes the collapse button so the output can be read properly
The button previously would cover the beggining of the output.
fixes #203 and fixes #273

output's collapse button size adjustment

---

jupyterthemes/layout/extras.less

The toolbar color when using the terminal app is set to `@body-bg` (white) in jupyter's [terminal.less](https://github.com/jupyter/notebook/blob/c2a2bcc4a7344652ae9229931fc2323ba67d7d4c/notebook/static/terminal/less/terminal.less#L5). That rule has higher specificity than the one in the theme's notebook.less file and so takes precedence, making the toolbar white.
This PR adds another rule with the same specificity to override it.

Fixed toolbar colors in the terminal app

---

jupyterthemes/layout/notebook.less

- Make .dynamic-buttons expand to fill horizontal space to render better when there are many buttons.
- Currently, .dynamic-buttons is hard-coded to width: 400px.
- When there are many dynamic buttons the 400px width causes overflow to another line.

Make .dynamic-buttons have width: 100%

---

jupyterthemes/layout/notebook.less

Fixes #349 
Previously:
With this change:

Change toolbar position to relative

---

jupyterthemes/__init__.py
jupyterthemes/stylefx.py

Customizations found in custom.js are overwritten when using JT. 
This PR adds a CLI argument (-kc or --keepcustom) that will restore customization from custom.js
Related issues: #426 #357 #415

Restore customization in custom.js

---

setup.py

The PyPi project still doesn't have a long_description:
This is because in the `setup.py`, you only start reading the README when a line contains `"Travis"`:
```python
if "Travis" in line.strip():
startReading = True
```
However, the README only contains the string *`travis`*:
This PR just reads everything in the README up to the `Monospace Fonts` header, since there's no reason to exclude the headers at the top.

Fix long_description for PyPi site

---

jupyterthemes/layout/codemirror.less

Added right padding to match CodeMirror to input_area and prevent cutting the last char of a long code line, relating to Issues #204 and #377 
I also suggest a new release to PyPI, so that new users won't have the same problem, as I also had an issue with the output padding that was already solved.

Fix Issues #204, #377

---

jupyterthemes/styles/gruvboxd.less

When the cursor was placed on a bracket the highlighting (blue on grey) made it difficult for me to tell _what_ was being matched (whether `)` or `}` or `]`). Also see #252.

Yellow matching brackets

---

jupyterthemes/layout/vim.less
jupyterthemes/stylefx.py

When vim-mode plugin is activated, cursor color preference is not applied to the fat-cursor or a style of the cursor in command mode as the below figure.
This PR fixes this.

Set color for fat-cursor of vim

---

jupyterthemes/__init__.py

According to `stylefx.style_layout` logic, there is user themes support (although, I didn't found it in docs).
```
if (os.path.isdir(styles_dir_user) and
'{}.less'.format(theme) in os.listdir(styles_dir_user)):
theme_relpath = os.path.relpath(
os.path.join(styles_dir_user, theme), package_dir)
else:
theme_relpath = os.path.relpath(
os.path.join(styles_dir, theme), package_dir)
```
But `get_themes()` function does not list user themes, and "Didn't recognize theme name" error message is shown.
This pull request solves it by adding user's `~/.jupyter-themes/styles/*.less` files to `get_themes()` listing.

fix user themes support
